<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>data_prep</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="data_prep_sept1_files/libs/clipboard/clipboard.min.js"></script>
<script src="data_prep_sept1_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="data_prep_sept1_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="data_prep_sept1_files/libs/quarto-html/popper.min.js"></script>
<script src="data_prep_sept1_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="data_prep_sept1_files/libs/quarto-html/anchor.min.js"></script>
<link href="data_prep_sept1_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="data_prep_sept1_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="data_prep_sept1_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="data_prep_sept1_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="data_prep_sept1_files/libs/bootstrap/bootstrap-917079515d91bccb85b543faf8aa8bb6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">data_prep</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">echo =</span> <span class="cn">FALSE</span>,       <span class="co"># Hide code by default</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">warning =</span> <span class="cn">FALSE</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">message =</span> <span class="cn">FALSE</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)   <span class="co"># for clean_names()</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'janitor'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    chisq.test, fisher.test</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tibble)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggbeeswarm)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'kableExtra' was built under R version 4.6.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'kableExtra'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    group_rows</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>OVERALL: I start by constructing the relevant info first (with the exception of excluding respondents who don’t consent), then describing what that info says, then I make exclusion (potentially additional flag) decisions last.</p>
<section id="basic-prep" class="level1">
<h1>1. Basic Prep</h1>
<p>Load data</p>
<p>Standardized and cleaned column names by (1) converting to lowerase, (2) replaces spaces with characters, removes accents, ensures uniqueness by adding numbers to duplicates, removing leading/trailing whitespace, creates syntatically valid names</p>
<p>Checked for changes, main change is made lowercase.</p>
<section id="a.-dp-labels" class="level4">
<h4 class="anchored" data-anchor-id="a.-dp-labels">a. D&amp;P Labels</h4>
<p>This happens first because it involves a column I want to drop in the next cleaning step.</p>
<p>Assign Deserving &amp; Power Blocks – redefine block using column names. Used the below to create block assignments for participants in A (n=900), B (n=898), and C (N=898) (to ultimately consolidate).</p>
<p>Explanation: Participants were sorted into 3 sections (ABC). For the deservingness and power questions, all 3 participant sections evaluated many of the same groups, but two of the three evaluated extra groups that participants in the other sections did not.</p>
<p>This shows up in the raw data:</p>
<ul>
<li>there are 3 versions of the same variables – one corresponding to participants in section a, another in section b, another in section c.</li>
</ul>
<p>Here, I am creating a block variable to keep track of what block each participant was sorted into, so that when I merge the disparate variables, it is still easy to know which group each participant was assigned to (thus, what groups they would have been prompted to evaluated and also important because it appears that the deserving questions for participants in block A were forced choice and snapped to increments of 10: not the case for B and C).</p>
</section>
<section id="b1.-re-name-variables-here-that-you-can-at-this-point" class="level4">
<h4 class="anchored" data-anchor-id="b1.-re-name-variables-here-that-you-can-at-this-point">b1. Re-name variables here that you can at this point</h4>
<p>Here, I’m renaming the ones that don’t involve cleaning or recoding – just where I can do a straightforward rename.</p>
<p>-Not doing deservingness and power here</p>
</section>
<section id="b2.-cleaned-data-frame-deleting-un-needed-vars" class="level4">
<h4 class="anchored" data-anchor-id="b2.-cleaned-data-frame-deleting-un-needed-vars">b2. Cleaned data frame, deleting un-needed vars</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  [1] "deserving_group_a_do_1"            "deserving_group_a_do_2"           
  [3] "deserving_group_a_do_3"            "deserving_group_a_do_4"           
  [5] "deserving_group_a_do_5"            "deserving_group_a_do_6"           
  [7] "deserving_group_a_do_7"            "deserving_group_a_do_8"           
  [9] "deserving_group_a_do_9"            "deserving_group_a_do_10"          
 [11] "deserving_group_a_do_11"           "deserving_group_a_do_12"          
 [13] "deserving_group_a_do_13"           "deserving_group_a_do_14"          
 [15] "deserving_group_a_do_15"           "deserving_group_a_do_16"          
 [17] "deserving_group_a_do_17"           "deserving_group_a_do_18"          
 [19] "deserving_group_a_do_19"           "deserving_group_a_do_20"          
 [21] "deserving_group_a_do_21"           "deserving_group_a_do_22"          
 [23] "deserving_group_a_do_23"           "deserving_group_a_do_24"          
 [25] "deserving_group_a_do_25"           "deserving_group_a_do_26"          
 [27] "deserving_group_a_do_27"           "deserving_group_a_do_28"          
 [29] "deserving_group_a_do_29"           "deserving_group_a_do_30"          
 [31] "deserving_group_a_do_31"           "deserving_group_a_do_32"          
 [33] "deserving_group_a_do_33"           "deserving_group_a_do_34"          
 [35] "deserving_group_a_do_35"           "deserving_group_a_do_36"          
 [37] "deserving_group_a_do_37"           "deserving_group_a_do_38"          
 [39] "deserving_group_a_do_39"           "deserving_group_a_do_40"          
 [41] "deserving_group_a_do_41"           "deserving_group_a_do_42"          
 [43] "deserving_group_a_do_43"           "deserving_group_a_do_44"          
 [45] "deserving_group_a_do_45"           "deserving_group_a_do_46"          
 [47] "deserving_group_a_do_47"           "deserving_group_a_do_48"          
 [49] "deserving_group_a_do_49"           "deserving_group_a_do_50"          
 [51] "deserving_group_a_do_51"           "deserving_group_a_do_52"          
 [53] "deserving_group_a_do_53"           "deserving_group_a_do_54"          
 [55] "deserving_group_a_do_55"           "deserving_group_a_do_56"          
 [57] "deserving_group_a_do_57"           "deserving_group_a_do_58"          
 [59] "deserving_group_a_do_59"           "deserving_group_a_do_60"          
 [61] "deserving_group_a_do_61"           "deserving_group_a_do_62"          
 [63] "deserving_group_a_do_63"           "deserving_group_a_do_64"          
 [65] "deserving_group_a_do_65"           "deserving_group_a_do_66"          
 [67] "power_group_a_do_1"                "power_group_a_do_2"               
 [69] "power_group_a_do_3"                "power_group_a_do_4"               
 [71] "power_group_a_do_5"                "power_group_a_do_6"               
 [73] "power_group_a_do_7"                "power_group_a_do_8"               
 [75] "power_group_a_do_9"                "power_group_a_do_10"              
 [77] "power_group_a_do_11"               "power_group_a_do_12"              
 [79] "power_group_a_do_13"               "power_group_a_do_14"              
 [81] "power_group_a_do_15"               "power_group_a_do_16"              
 [83] "power_group_a_do_17"               "power_group_a_do_18"              
 [85] "power_group_a_do_19"               "power_group_a_do_20"              
 [87] "power_group_a_do_21"               "power_group_a_do_22"              
 [89] "power_group_a_do_23"               "power_group_a_do_24"              
 [91] "power_group_a_do_25"               "power_group_a_do_26"              
 [93] "power_group_a_do_27"               "power_group_a_do_28"              
 [95] "power_group_a_do_29"               "power_group_a_do_30"              
 [97] "power_group_a_do_31"               "power_group_a_do_32"              
 [99] "power_group_a_do_33"               "power_group_a_do_34"              
[101] "power_group_a_do_35"               "power_group_a_do_36"              
[103] "power_group_a_do_37"               "power_group_a_do_38"              
[105] "power_group_a_do_39"               "power_group_a_do_40"              
[107] "power_group_a_do_41"               "power_group_a_do_42"              
[109] "power_group_a_do_43"               "power_group_a_do_44"              
[111] "power_group_a_do_45"               "power_group_a_do_46"              
[113] "power_group_a_do_47"               "power_group_a_do_48"              
[115] "power_group_a_do_49"               "power_group_a_do_66"              
[117] "power_group_a_do_50"               "power_group_a_do_51"              
[119] "power_group_a_do_52"               "power_group_a_do_53"              
[121] "power_group_a_do_54"               "power_group_a_do_55"              
[123] "power_group_a_do_56"               "power_group_a_do_57"              
[125] "power_group_a_do_58"               "power_group_a_do_59"              
[127] "power_group_a_do_60"               "power_group_a_do_61"              
[129] "power_group_a_do_62"               "power_group_a_do_63"              
[131] "power_group_a_do_64"               "deserving_group_b_do_1"           
[133] "deserving_group_b_do_2"            "deserving_group_b_do_3"           
[135] "deserving_group_b_do_4"            "deserving_group_b_do_5"           
[137] "deserving_group_b_do_6"            "deserving_group_b_do_7"           
[139] "deserving_group_b_do_8"            "deserving_group_b_do_9"           
[141] "deserving_group_b_do_10"           "deserving_group_b_do_11"          
[143] "deserving_group_b_do_12"           "deserving_group_b_do_13"          
[145] "deserving_group_b_do_14"           "deserving_group_b_do_15"          
[147] "deserving_group_b_do_16"           "deserving_group_b_do_17"          
[149] "deserving_group_b_do_18"           "deserving_group_b_do_19"          
[151] "deserving_group_b_do_20"           "deserving_group_b_do_21"          
[153] "deserving_group_b_do_22"           "deserving_group_b_do_23"          
[155] "deserving_group_b_do_24"           "deserving_group_b_do_25"          
[157] "deserving_group_b_do_26"           "deserving_group_b_do_27"          
[159] "deserving_group_b_do_28"           "deserving_group_b_do_29"          
[161] "deserving_group_b_do_30"           "deserving_group_b_do_31"          
[163] "deserving_group_b_do_32"           "deserving_group_b_do_33"          
[165] "deserving_group_b_do_34"           "deserving_group_b_do_35"          
[167] "deserving_group_b_do_36"           "deserving_group_b_do_37"          
[169] "deserving_group_b_do_38"           "deserving_group_b_do_39"          
[171] "deserving_group_b_do_40"           "deserving_group_b_do_41"          
[173] "deserving_group_b_do_42"           "deserving_group_b_do_43"          
[175] "deserving_group_b_do_44"           "deserving_group_b_do_45"          
[177] "deserving_group_b_do_46"           "deserving_group_b_do_47"          
[179] "deserving_group_b_do_48"           "deserving_group_b_do_49"          
[181] "deserving_group_b_do_50"           "deserving_group_b_do_51"          
[183] "deserving_group_b_do_52"           "deserving_group_b_do_53"          
[185] "deserving_group_b_do_54"           "deserving_group_b_do_55"          
[187] "deserving_group_b_do_56"           "deserving_group_b_do_57"          
[189] "deserving_group_b_do_58"           "deserving_group_b_do_59"          
[191] "deserving_group_b_do_60"           "deserving_group_b_do_61"          
[193] "deserving_group_b_do_62"           "deserving_group_b_do_63"          
[195] "power_group_b_do_1"                "power_group_b_do_2"               
[197] "power_group_b_do_3"                "power_group_b_do_4"               
[199] "power_group_b_do_5"                "power_group_b_do_6"               
[201] "power_group_b_do_7"                "power_group_b_do_8"               
[203] "power_group_b_do_9"                "power_group_b_do_10"              
[205] "power_group_b_do_11"               "power_group_b_do_12"              
[207] "power_group_b_do_13"               "power_group_b_do_14"              
[209] "power_group_b_do_15"               "power_group_b_do_16"              
[211] "power_group_b_do_17"               "power_group_b_do_18"              
[213] "power_group_b_do_19"               "power_group_b_do_20"              
[215] "power_group_b_do_21"               "power_group_b_do_22"              
[217] "power_group_b_do_23"               "power_group_b_do_24"              
[219] "power_group_b_do_25"               "power_group_b_do_26"              
[221] "power_group_b_do_27"               "power_group_b_do_28"              
[223] "power_group_b_do_29"               "power_group_b_do_30"              
[225] "power_group_b_do_31"               "power_group_b_do_32"              
[227] "power_group_b_do_33"               "power_group_b_do_34"              
[229] "power_group_b_do_35"               "power_group_b_do_36"              
[231] "power_group_b_do_37"               "power_group_b_do_38"              
[233] "power_group_b_do_39"               "power_group_b_do_40"              
[235] "power_group_b_do_41"               "power_group_b_do_42"              
[237] "power_group_b_do_43"               "power_group_b_do_44"              
[239] "power_group_b_do_45"               "power_group_b_do_46"              
[241] "power_group_b_do_47"               "power_group_b_do_48"              
[243] "power_group_b_do_49"               "power_group_b_do_50"              
[245] "power_group_b_do_51"               "power_group_b_do_52"              
[247] "power_group_b_do_53"               "power_group_b_do_54"              
[249] "power_group_b_do_55"               "power_group_b_do_56"              
[251] "power_group_b_do_57"               "power_group_b_do_58"              
[253] "power_group_b_do_59"               "power_group_b_do_60"              
[255] "power_group_b_do_61"               "power_group_b_do_62"              
[257] "power_group_b_do_63"               "deserving_group_c_do_1"           
[259] "deserving_group_c_do_2"            "deserving_group_c_do_3"           
[261] "deserving_group_c_do_4"            "deserving_group_c_do_5"           
[263] "deserving_group_c_do_6"            "deserving_group_c_do_7"           
[265] "deserving_group_c_do_8"            "deserving_group_c_do_9"           
[267] "deserving_group_c_do_10"           "deserving_group_c_do_11"          
[269] "deserving_group_c_do_12"           "deserving_group_c_do_13"          
[271] "deserving_group_c_do_14"           "deserving_group_c_do_15"          
[273] "deserving_group_c_do_16"           "deserving_group_c_do_17"          
[275] "deserving_group_c_do_18"           "deserving_group_c_do_19"          
[277] "deserving_group_c_do_20"           "deserving_group_c_do_21"          
[279] "deserving_group_c_do_22"           "deserving_group_c_do_23"          
[281] "deserving_group_c_do_24"           "deserving_group_c_do_25"          
[283] "deserving_group_c_do_26"           "deserving_group_c_do_27"          
[285] "deserving_group_c_do_28"           "deserving_group_c_do_29"          
[287] "deserving_group_c_do_30"           "deserving_group_c_do_31"          
[289] "deserving_group_c_do_32"           "deserving_group_c_do_33"          
[291] "deserving_group_c_do_34"           "deserving_group_c_do_35"          
[293] "deserving_group_c_do_36"           "deserving_group_c_do_37"          
[295] "deserving_group_c_do_38"           "deserving_group_c_do_39"          
[297] "deserving_group_c_do_40"           "deserving_group_c_do_41"          
[299] "deserving_group_c_do_42"           "deserving_group_c_do_43"          
[301] "deserving_group_c_do_44"           "deserving_group_c_do_45"          
[303] "deserving_group_c_do_46"           "deserving_group_c_do_47"          
[305] "deserving_group_c_do_48"           "deserving_group_c_do_49"          
[307] "deserving_group_c_do_50"           "deserving_group_c_do_51"          
[309] "deserving_group_c_do_52"           "deserving_group_c_do_53"          
[311] "deserving_group_c_do_54"           "deserving_group_c_do_55"          
[313] "deserving_group_c_do_56"           "deserving_group_c_do_57"          
[315] "deserving_group_c_do_58"           "deserving_group_c_do_59"          
[317] "deserving_group_c_do_60"           "deserving_group_c_do_61"          
[319] "deserving_group_c_do_62"           "deserving_group_c_do_63"          
[321] "deserving_group_c_do_64"           "power_group_c_do_1"               
[323] "power_group_c_do_2"                "power_group_c_do_3"               
[325] "power_group_c_do_4"                "power_group_c_do_5"               
[327] "power_group_c_do_6"                "power_group_c_do_7"               
[329] "power_group_c_do_8"                "power_group_c_do_9"               
[331] "power_group_c_do_10"               "power_group_c_do_11"              
[333] "power_group_c_do_12"               "power_group_c_do_13"              
[335] "power_group_c_do_14"               "power_group_c_do_15"              
[337] "power_group_c_do_16"               "power_group_c_do_17"              
[339] "power_group_c_do_18"               "power_group_c_do_19"              
[341] "power_group_c_do_20"               "power_group_c_do_21"              
[343] "power_group_c_do_22"               "power_group_c_do_23"              
[345] "power_group_c_do_24"               "power_group_c_do_25"              
[347] "power_group_c_do_26"               "power_group_c_do_27"              
[349] "power_group_c_do_28"               "power_group_c_do_29"              
[351] "power_group_c_do_30"               "power_group_c_do_31"              
[353] "power_group_c_do_32"               "power_group_c_do_33"              
[355] "power_group_c_do_34"               "power_group_c_do_35"              
[357] "power_group_c_do_36"               "power_group_c_do_37"              
[359] "power_group_c_do_38"               "power_group_c_do_39"              
[361] "power_group_c_do_40"               "power_group_c_do_41"              
[363] "power_group_c_do_42"               "power_group_c_do_43"              
[365] "power_group_c_do_44"               "power_group_c_do_45"              
[367] "power_group_c_do_46"               "power_group_c_do_47"              
[369] "power_group_c_do_48"               "power_group_c_do_49"              
[371] "power_group_c_do_50"               "power_group_c_do_51"              
[373] "power_group_c_do_52"               "power_group_c_do_53"              
[375] "power_group_c_do_54"               "power_group_c_do_55"              
[377] "power_group_c_do_56"               "power_group_c_do_57"              
[379] "power_group_c_do_58"               "power_group_c_do_59"              
[381] "power_group_c_do_60"               "power_group_c_do_61"              
[383] "power_group_c_do_62"               "power_group_c_do_63"              
[385] "power_group_c_do_64"               "q4_do_1"                          
[387] "q4_do_2"                           "q4_do_3"                          
[389] "q4_do_4"                           "q4_do_5"                          
[391] "q4_do_6"                           "q4_do_7"                          
[393] "q4_do_8"                           "q4_do_9"                          
[395] "q4_do_10"                          "q4_do_11"                         
[397] "q63_do_1"                          "q63_do_2"                         
[399] "q63_do_3"                          "q74_do_1"                         
[401] "q74_do_2"                          "q74_do_3"                         
[403] "q74_do_4"                          "q74_do_5"                         
[405] "q74_do_6"                          "fl_8_do_deserving_power_block_a"  
[407] "fl_8_do_deserving_power_block_b"   "fl_8_do_deserving_power_block_c"  
[409] "ration_block_do_q8"                "ration_block_do_q7"               
[411] "ration_block_do_q6"                "police_block_do_q15"              
[413] "police_block_do_q25"               "police_block_do_q62"              
[415] "medicaid_medicare_ui_block_do_q19" "medicaid_medicare_ui_block_do_q18"
[417] "medicaid_medicare_ui_block_do_q20" "scaleblock_do_q104"               
[419] "scaleblock_do_q68"                 "race_women_efficacy_block_do_q29" 
[421] "race_women_efficacy_block_do_q38"  "race_women_efficacy_block_do_q37" 
[423] "race_women_efficacy_block_do_q110" "race_women_efficacy_block_do_q36" 
[425] "race_women_efficacy_block_do_q111" "race_women_efficacy_block_do_q35" 
[427] "race_women_efficacy_block_do_q34"  "race_women_efficacy_block_do_q112"
[429] "race_women_efficacy_block_do_q33"  "race_women_efficacy_block_do_q32" 
[431] "race_women_efficacy_block_do_q43"  "race_women_efficacy_block_do_q31" 
[433] "race_women_efficacy_block_do_q42"  "race_women_efficacy_block_do_q30" 
[435] "race_women_efficacy_block_do_q41"  "race_women_efficacy_block_do_q40" </code></pre>
</div>
</div>
</section>
<section id="c.-drop-non-consenters" class="level3">
<h3 class="anchored" data-anchor-id="c.-drop-non-consenters">c.&nbsp;Drop non-consenters</h3>
<p>Still using “raw data”</p>
</section>
</section>
<section id="initial-clean-quality" class="level1">
<h1>2. Initial Clean &amp; Quality</h1>
<section id="a.-attn-checks" class="level3">
<h3 class="anchored" data-anchor-id="a.-attn-checks">a. attn checks</h3>
<p>uncleaned: q9, character, can be 1 2 3 4 NA 3 -99 –see 2095 passed, 599 did not q17, character, lots of different responses -2063 passed, 631 not q114_4, character can be 6 5 NA 4 -99</p>
<ul>
<li>create flags for passed/not each check and people who failed all</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Mode   FALSE    TRUE 
logical     599    2095 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
FALSE  TRUE 
  628  2066 </code></pre>
</div>
</div>
<p>attn_q9_pass, attn_check_q17, attn_q114_pass</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
   0    1    2    3 
 599   29  462 1604 </code></pre>
</div>
</div>
<p>1,604 respondents passed all 3 attn checks 599 did not supply correct answers none of them 32 passed 1 459 passed 2</p>
</section>
<section id="b.-survey-duration" class="level3">
<h3 class="anchored" data-anchor-id="b.-survey-duration">b. survey duration</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
    0.05    14.70    25.35   138.16    44.14 13975.55 </code></pre>
</div>
</div>
<p>median: 25.35</p>
<p>Grouping ppl into speed categories</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
    0.05    14.70    25.35   138.16    44.14 13975.55 </code></pre>
</div>
</div>
</section>
<section id="c.-progressfinished" class="level3">
<h3 class="anchored" data-anchor-id="c.-progressfinished">c.&nbsp;progress/finished</h3>
<p>visualization of respondent progress</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data_prep_sept1_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="d.-nas-completion-of-vars---end" class="level3">
<h3 class="anchored" data-anchor-id="d.-nas-completion-of-vars---end">d.&nbsp;NAs &amp; completion of vars -&gt; end</h3>
</section>
<section id="des-and-pwr-consolidation" class="level3">
<h3 class="anchored" data-anchor-id="des-and-pwr-consolidation">***Des and pwr consolidation</h3>
<p>Objective: consolidate blocks (i.e.&nbsp;so only 1 Incarcerated People/Prisoners)</p>
<p>ABC loop to consolidate groups. Verified. After below, dataset in memory has unified variables.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [16] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [31] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [46] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [61] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [76] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [91] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[106] TRUE TRUE TRUE</code></pre>
</div>
</div>
<p>LIMITED Deserving/power for 1 group only: recode groups directly</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "All group-specific variables created successfully."</code></pre>
</div>
</div>
<p>Checking this worked before removing the old variables</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>character(0)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>     d_black_afam_abc      d_native_ind_abc         d_asianam_abc 
                    0                     0                     0 
     d_latino_his_abc         d_whiteam_abc       d_mideastam_abc 
                    0                     0                     0 
       d_incwomen_abc      d_collegewom_abc          d_enviro_abc 
                    0                     0                     0 
      d_feminists_abc d_proabort_choice_abc       d_abortprov_abc 
                    0                     0                     0 
   d_welfare_tanf_abc    d_fstamps_snap_abc          d_unions_abc 
                    0                     0                     0 
       d_medicaid_abc        d_medicare_abc      d_unemployed_abc 
                    0                     0                     0 
         d_police_abc         d_poorfam_abc         d_wealthy_abc 
                    0                     0                     0 
       d_teachers_abc     d_sci_experts_abc           d_child_abc 
                    0                     0                     0 
           d_crim_abc     d_incppl_pris_abc        d_homeless_abc 
                    0                     0                     0 
     d_immigrants_abc    d_unauth_undoc_abc       d_gunowners_abc 
                    0                     0                     0 
         d_voters_abc            d_lgbt_abc           d_trans_abc 
                    0                     0                     0 
      d_transkids_abc         d_gunmans_abc             d_ice_abc 
                    0                     0                     0 
         d_socmed_abc             d_nra_abc         d_bigbank_abc 
                    0                     0                     0 
        d_bigcorp_abc             d_uni_abc         d_comcoll_abc 
                    0                     0                     0 
    d_noncit_parent_a        d_incparents_a            d_hsteen_a 
                    0                     0                     0 
          d_athiest_a              d_cath_a              d_evan_a 
                    0                     0                     0 
             d_jews_a               d_pal_a            d_muslim_a 
                    0                     0                     0 
         d_blackwom_a          d_blackmen_a               d_lds_a 
                    0                     0                     0 
          d_longcov_a              d_exon_a              d_weed_a 
                    0                     0                     0 
           d_opioid_a          d_whitecol_a              d_tech_a 
                    0                     0                     0 
          d_smokers_a              d_genx_a            d_boomer_a 
                    0                     0                     0 
             d_mill_a              d_genz_a             d_metoo_b 
                    0                     0                     0 
        d_christnat_b           d_ruralam_b           d_urbanam_b 
                    0                     0                     0 
         d_suburbam_b           d_billion_b               d_blm_b 
                    0                     0                     0 
             d_maga_b             d_progs_b               d_soc_b 
                    0                     0                     0 
        d_proudboys_b            d_attnys_b          d_military_b 
                    0                     0                     0 
             d_vets_b             d_solds_b        d_essentials_b 
                    0                     0                     0 
           d_nurses_b               d_drs_b              d_dems_b 
                    0                     0                     0 
             d_reps_b             d_media_b           d_bluecol_c 
                    0                     0                     0 
          d_working_c          d_midclass_c       d_migrantwork_c 
                    0                     0                     0 
         d_smallbiz_c         d_taxpayers_c           d_elderly_c 
                    0                     0                     0 
             d_moms_c           d_retires_c      d_sexoffenders_c 
                    0                     0                     0 
      d_sexhar_vict_c      d_sexharrasser_c       d_formerlyinc_c 
                    0                     0                     0 
          d_homeown_c           d_regufee_c        d_gunvi_vict_c 
                    0                     0                     0 
     d_polbrut_vict_c             d_unins_c           d_mentill_c 
                    0                     0                     0 
             d_aids_c               d_gay_c          d_lesbians_c 
                    0                     0                     0 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 3
   block deserving_group_a_26 d_incppl_pris_abc
   &lt;chr&gt; &lt;chr&gt;                            &lt;dbl&gt;
 1 A     70                                  70
 2 A     -99                                 NA
 3 A     50                                  50
 4 A     -99                                 NA
 5 A     20                                  20
 6 A     70                                  70
 7 A     40                                  40
 8 A     80                                  80
 9 A     50                                  50
10 A     70                                  70
11 A     80                                  80
12 A     50                                  50
13 A     100                                100
14 A     40                                  40
15 A     80                                  80
16 A     80                                  80
17 A     40                                  40
18 A     50                                  50
19 A     20                                  20
20 A     40                                  40</code></pre>
</div>
</div>
<p>Variables I can now prepare to drop</p>
<p>Check/inspect to make sure right ones to drop</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 385</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "deserving_group_a_1"  "deserving_group_a_2"  "deserving_group_a_3" 
 [4] "deserving_group_a_4"  "deserving_group_a_5"  "deserving_group_a_6" 
 [7] "deserving_group_a_7"  "deserving_group_a_8"  "deserving_group_a_9" 
[10] "deserving_group_a_10" "deserving_group_a_11" "deserving_group_a_12"
[13] "deserving_group_a_13" "deserving_group_a_14" "deserving_group_a_15"
[16] "deserving_group_a_16" "deserving_group_a_17" "deserving_group_a_18"
[19] "deserving_group_a_19" "deserving_group_a_20"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "power_group_c_45" "power_group_c_46" "power_group_c_47" "power_group_c_48"
 [5] "power_group_c_49" "power_group_c_50" "power_group_c_51" "power_group_c_52"
 [9] "power_group_c_53" "power_group_c_54" "power_group_c_55" "power_group_c_56"
[13] "power_group_c_57" "power_group_c_58" "power_group_c_59" "power_group_c_60"
[17] "power_group_c_61" "power_group_c_62" "power_group_c_63" "power_group_c_64"</code></pre>
</div>
</div>
<p>Save pre-dropped version</p>
<p>Save for analysis dataset without block-spec/deserv vars</p>
</section>
<section id="d.-nas-completion-of-vars" class="level3">
<h3 class="anchored" data-anchor-id="d.-nas-completion-of-vars">2d. NAs &amp; completion of vars</h3>
<p>I want to understand basic distribution of missingness/NAs, but because of the block specific variables I need to do so seperately for the trhee.</p>
<p>###e. patterns</p>
<p>If for the deservingness questions, respondent has set all to same number or many in a row same number</p>
<p>if all block a, block b, or block c vars are same number</p>
<p>items under a question – all are ‘strongly support’ or ‘no/unsure’ etc</p>
<p>“q15_1”, “local_police”, “q15_3”, “q15_4”, “charge_police”,</p>
<p>“q25_1”, “q25_2”, “q25_3”, “q25_4”,</p>
<p>“q23_2”, “q23_2”,“q23_7”,</p>
<p>“q32”, “q33”, “q34”, “q35”, “q36”, “q37”, “q38”,</p>
<p>“q51_1”, “q51_2”, “q51_3”, “q51_4”, “q51_5”, “q51_6”, “q51_7”, “q51_8”,</p>
</section>
</section>
<section id="description-of-consented-pre-screening-sample" class="level1">
<h1>5. Description of Consented, pre-screening sample</h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 320</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2694</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  block     n
  &lt;chr&gt; &lt;int&gt;
1 A       898
2 B       898
3 C       898</code></pre>
</div>
</div>
<section id="attention-checks" class="level2">
<h2 class="anchored" data-anchor-id="attention-checks">attention checks</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  attn_pass_count     n
            &lt;dbl&gt; &lt;int&gt;
1               0   599
2               1    29
3               2   462
4               3  1604</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  attn_answered_count     n
                &lt;int&gt; &lt;int&gt;
1                   0   396
2                   1   223
3                   2   412
4                   3  1663</code></pre>
</div>
</div>
<p>Overall, 1,604 respondents passed all 3 checks. 462 passed 2, 29 passed 1, and 599 respondents “failed” all 3 checks – or they did not supply correct answers.This can include NAs.</p>
<p>table:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 9
      n q9_pass_n q9_pass_pct attn_q9_typo_n attn_q9_typo_pct q17_pass_n
  &lt;int&gt;     &lt;int&gt;       &lt;dbl&gt;          &lt;int&gt;            &lt;dbl&gt;      &lt;int&gt;
1  2694      2095        77.8            182             6.76       2066
# ℹ 3 more variables: q17_pass_pct &lt;dbl&gt;, q114_pass_n &lt;int&gt;,
#   q114_pass_pct &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Among pre-cleaned, consenting respondents (n = 2694), 78% (n=2095) passed the first check, 6.8% (n = 182) at least selected “strongly” (selected strongly disagree instead of strongly agree); 76% (n = 2066) passed the second attention check by typing purple or a very mild mispelling of it (ommitting a single letter, for example); and 60% (n = 1604) passed the last attention check or indicated that they never use a fake social media platform.</p>
<p>table factoring in answered</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 12
  check total_n answered_n nonanswer_n pass_n wrong_n nonpass_n answered_pct
  &lt;chr&gt;   &lt;int&gt;      &lt;int&gt;       &lt;int&gt;  &lt;int&gt;   &lt;int&gt;     &lt;int&gt;        &lt;dbl&gt;
1 Q9       2694       2298         396   2095     203       599         85.3
2 Q17      2694       2075         619   2066       9       628         77.0
3 Q114     2694       1663        1031   1604      59      1090         61.7
# ℹ 4 more variables: pass_pct_all &lt;dbl&gt;, pass_pct_answered &lt;dbl&gt;,
#   nonanswer_pct_of_nonpass &lt;dbl&gt;, wrong_pct_answered &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Attention checks themselves actually show respondent drop-off. The first check was answered by 2,298 respondents, the second was answered by 2,075 respondents, and the third was only answered by 1,663 respondents. For the first, of those who answered, 203 answered incorrectly and 2,095 answered correctly. For the second, 9 answered incorrectly and 2,066 passed. For the third, 59 answered incorrectly and 1,604 passed.</p>
<p>**save that table for overleaf.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 3
  attn_pass_count attn_answered_count     n
            &lt;dbl&gt;               &lt;int&gt; &lt;int&gt;
1               0                   0   396
2               0                   1   202
3               0                   3     1
4               1                   1    21
5               1                   2     8
6               2                   2   404
7               2                   3    58
8               3                   3  1604</code></pre>
</div>
</div>
</section>
<section id="duration" class="level2">
<h2 class="anchored" data-anchor-id="duration">duration</h2>
<p>what does survey duration actually look like?</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data_prep_sept1_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
    0.05    14.70    25.35   138.16    44.14 13975.55 </code></pre>
</div>
</div>
<p>Took respondents from less than a second to days to “complete” the survey. flags: -sub_8 -sub_12 -sub_20 -sub_30 -over_52 -over_180</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 13
      n sub_8_n sub_8_pct sub_12_n sub_12_pct sub_20_n sub_20_pct sub_30_n
  &lt;int&gt;   &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;
1  2694     368      13.7      570       21.2     1021       37.9     1595
# ℹ 5 more variables: sub_30_pct &lt;dbl&gt;, over_52_n &lt;dbl&gt;, over_52_pct &lt;dbl&gt;,
#   over_180_n &lt;dbl&gt;, over_180_pct &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Of the 2,694 consenting respondents, 13% (n = 352) reached the end of the survey in less or equal to 8 minutes; 20% (n = 539) in less than or equal to 12 minutes; 38% (n = 1021) in less than or equal to 20 minutes, 59% (n = 1592) in or less than 30, 21% (n = 563) in 52 minutes or more, and 7% or 200 respondents took two hours or more.</p>
</section>
<section id="finishers" class="level2">
<h2 class="anchored" data-anchor-id="finishers">finishers</h2>
<p>nonfinisher</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
      n finished_n finished_pct nonfinished_n nonfinished_pct
  &lt;int&gt;      &lt;int&gt;        &lt;dbl&gt;         &lt;dbl&gt;           &lt;dbl&gt;
1  2694       2231        0.828           463           0.172</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
   0    1 
 463 2231 </code></pre>
</div>
</div>
<p>Of the 2,694 consenting respondents, 83% finished (as in, reached the end of the survey, irregardless of skipped questions) (n = 2,231) and 17% did not (n = 463).</p>
</section>
<section id="missingness" class="level2">
<h2 class="anchored" data-anchor-id="missingness">missingness?</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   2.00    2.00    3.00   67.39  127.00  247.00 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   2.00    2.00    3.00   64.74  127.00  224.00 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.000   0.000   0.000   2.647   0.000  23.000 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data_prep_sept1_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 8
  finished     n min_na q1_na median_na mean_na q3_na max_na
  &lt;chr&gt;    &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
1 0          463     35   182       245   212.    246    247
2 1         2231      2     2         3    37.3   127    208</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 7
  block     n median_na mean_na q75_na q90_na max_na
  &lt;chr&gt; &lt;int&gt;     &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
1 A       898         3    64.4    128    182    247
2 B       898         3    64.2    127    182    245
3 C       898         3    73.5    127    246    246</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 6
  progress_group     n median_na mean_na min_na max_na
  &lt;chr&gt;          &lt;int&gt;     &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
1 100%            2231         3    37.3      2    208
2 25–&lt;50%           42       100   103.      70    170
3 50–&lt;75%            1        54    54       54     54
4 75–&lt;100%           1        35    35       35     35
5 &lt;25%             419       246   224.     127    247</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 6
  attn_answered_count     n median_na mean_na median_progress pct_finished
                &lt;int&gt; &lt;int&gt;     &lt;dbl&gt;   &lt;dbl&gt;           &lt;dbl&gt;        &lt;dbl&gt;
1                   0   396       246  229.                 7        0.505
2                   1   223       145  147.               100       90.6  
3                   2   412       127  123.               100       88.6  
4                   3  1663         3    4.48             100       99.9  </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 8
  finished     n median_progress median_na median_common_na median_block_na
  &lt;chr&gt;    &lt;int&gt;           &lt;dbl&gt;     &lt;dbl&gt;            &lt;dbl&gt;           &lt;dbl&gt;
1 0          463               7       245              224              21
2 1         2231             100         3                3               0
# ℹ 2 more variables: median_attn_answered &lt;int&gt;, median_attn_passed &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="clustering-of-indicators" class="level2">
<h2 class="anchored" data-anchor-id="clustering-of-indicators">clustering of indicators?</h2>
<p>overlap summary</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 12
  check total_n answered_n nonanswer_n pass_n wrong_n nonpass_n answered_pct
  &lt;chr&gt;   &lt;int&gt;      &lt;int&gt;       &lt;int&gt;  &lt;int&gt;   &lt;int&gt;     &lt;int&gt;        &lt;dbl&gt;
1 Q9       2694       2298         396   2095     203       599         85.3
2 Q17      2694       2075         619   2066       9       628         77.0
3 Q114     2694       1663        1031   1604      59      1090         61.7
# ℹ 4 more variables: pass_pct_all &lt;dbl&gt;, pass_pct_answered &lt;dbl&gt;,
#   nonanswer_pct_of_nonpass &lt;dbl&gt;, wrong_pct_answered &lt;dbl&gt;</code></pre>
</div>
</div>
<section id="enough-usable-measurements" class="level3">
<h3 class="anchored" data-anchor-id="enough-usable-measurements">enough usable measurements?</h3>
<p>Ie, did respondents supply enough of the questionnaire to furnish usable measurements?</p>
<p>Among people who broke off—or among finishers with substantial missingness—what analytically important information is actually present?</p>
<p>used variables</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>used_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"d_crim_abc"</span>, <span class="st">"d_incppl_pris_abc"</span>,<span class="st">"d_incwomen_abc"</span>,<span class="st">"local_police"</span>, <span class="st">"local_police"</span>, <span class="st">"police_tracker"</span>, <span class="st">"police_training"</span>, <span class="st">"charge_police"</span>,</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="st">"dpen"</span>, <span class="st">"min_wage"</span>, <span class="st">"free_calls"</span>, <span class="st">"ed_funds"</span>, <span class="st">"incarc_raw"</span>, <span class="st">"knowincarc_raw"</span>, <span class="st">"noincarc_raw"</span>, <span class="st">"vict_raw"</span>, <span class="st">"knowvict_raw"</span>, <span class="st">"novict_raw"</span>, <span class="st">"lwop"</span>, <span class="st">"alt_sentencing"</span>, <span class="st">"post_felony_vote"</span>,<span class="st">"jail_access"</span>, <span class="st">"prison_purpose"</span>,<span class="st">"White"</span>, <span class="st">"Black"</span>, <span class="st">"Hisp_Latino"</span>, <span class="st">"Asian_Am"</span>, <span class="st">"Native_Am"</span>, <span class="st">"Pac_Island"</span>, <span class="st">"MENA"</span>, <span class="st">"race_notlisted"</span>,<span class="st">"dem101"</span>,<span class="st">"fire_rare"</span>, <span class="st">"fire_privilege"</span>, <span class="st">"fire_angry"</span>, <span class="st">"fire_fear"</span>, <span class="st">"aa_special_favors"</span>, <span class="st">"aa_been_cheated"</span>, <span class="st">"aa_try_harder"</span>, <span class="st">"legacy_slavery"</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>used_var_missing <span class="ot">&lt;-</span> raw_data <span class="sc">%&gt;%</span> </span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">across</span>(</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">all_of</span>(used_vars),</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>      <span class="sc">~</span><span class="fu">sum</span>(<span class="fu">is.na</span>(.))</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">everything</span>(),</span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"variable"</span>,</span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"n_missing"</span></span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb48-17"><a href="#cb48-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb48-18"><a href="#cb48-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_answered =</span> <span class="fu">nrow</span>(raw_data)<span class="sc">-</span> n_missing,</span>
<span id="cb48-19"><a href="#cb48-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_missing =</span> n_missing<span class="sc">/</span><span class="fu">nrow</span>(raw_data) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb48-20"><a href="#cb48-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_answered =</span> n_answered<span class="sc">/</span><span class="fu">nrow</span>(raw_data) <span class="sc">*</span><span class="dv">100</span></span>
<span id="cb48-21"><a href="#cb48-21" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb48-22"><a href="#cb48-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(pct_missing))</span>
<span id="cb48-23"><a href="#cb48-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-24"><a href="#cb48-24" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(used_var_missing)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>for overleaf</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 232 × 3
   variable   n_missing pct_missing
   &lt;chr&gt;          &lt;int&gt;       &lt;dbl&gt;
 1 q112            2694       100  
 2 q109            2297        85.3
 3 dem             2071        76.9
 4 born_again      1412        52.4
 5 self_ideo       1082        40.2
 6 White           1082        40.2
 7 Black           1082        40.2
 8 Native_Am       1082        40.2
 9 Asian_Am        1082        40.2
10 Pac_Island      1082        40.2
# ℹ 222 more rows</code></pre>
</div>
</div>
<p>Branch questions: 109 112 dem q53</p>
<p>Demographics q51_n (racial dem) q56 (gender) (_1 is women, _2 man, _3 queer, _4 other)</p>
<p>Info I will need about respondents who answer DVs - race - gender - political identity</p>
<p>Race vars uncleaned are 0, 1, NA, -99</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "character"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
 -99    0    1 &lt;NA&gt; 
   3  425 1184 1082 </code></pre>
</div>
</div>
<p>425 not-white respondents who made it to this question 1184 white respondents who made it to this question 1082 started but didn’t make it to this question</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "1"   "0"   NA    "-99"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
 -99    0    1 &lt;NA&gt; 
   3 1341  268 1082 </code></pre>
</div>
</div>
<p>268 black respondents 1341 not black respondents 1082 NA</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
 -99    0    1 &lt;NA&gt; 
   3 1372  237 1082 </code></pre>
</div>
</div>
<p>237 Hispanic respondents 1372 not hispanic respondents 1082 NA</p>
</section>
</section>
</section>
<section id="flag-and-or-drop" class="level1">
<h1>6. Flag and or drop</h1>
<section id="attn-checks" class="level3">
<h3 class="anchored" data-anchor-id="attn-checks">attn checks</h3>
</section>
<section id="duration-1" class="level3">
<h3 class="anchored" data-anchor-id="duration-1">duration</h3>
<p>-already did sub 8 through 30, over 52 over 180 Hillygus: standard is to drop 1/3 median, flag 1/2 median</p>
<p>median: 25.35 1/3 is 8.43</p>
</section>
<section id="progressfinished" class="level3">
<h3 class="anchored" data-anchor-id="progressfinished">progress/finished</h3>
<p>DROP – faster than 1/3 the median, so sub 8.43 min responders</p>
<p>I looked at the 8.43 people. Among them, 277 did not answer any of the 3 attentioon checks. These folks (faster than a third the median and didn not answer attention checks) can go.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
FALSE  TRUE 
 2417   277 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 277 × 5
   respondent_id      duration_minutes attn_answered_count attn_pass_count
   &lt;chr&gt;                         &lt;dbl&gt;               &lt;int&gt;           &lt;dbl&gt;
 1 iP4a7f33c2ba24c0ef            0.1                     0               0
 2 iPbed21bf0d15adf39            1.68                    0               0
 3 iPcc9072b73bc2d0e0            1                       0               0
 4 iP2ca8f1159704a395            4.17                    0               0
 5 iPea07e47873b4cea0            0.867                   0               0
 6 iP6ebe05656b32ef23            0.95                    0               0
 7 iPfd843fd266982a94            3.35                    0               0
 8 iP109d083129f37429            0.467                   0               0
 9 iP4d89bded1964c00e            4.2                     0               0
10 iP822a81e573606fd8            0.117                   0               0
# ℹ 267 more rows
# ℹ 1 more variable: attn_wrong_count &lt;dbl&gt;</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
      n
  &lt;int&gt;
1  2417</code></pre>
</div>
</div>
<p>This brings the N to 2417.</p>
<p>What about those who were faster than 1/3 the median but failed all three?</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
FALSE  TRUE 
 2416     1 </code></pre>
</div>
</div>
<p>There’s just one. We can remove that person.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
      n
  &lt;int&gt;
1  2416</code></pre>
</div>
</div>
<p>Now the N is 2416.</p>
<p>Remaining respondents who were under a third of the median?</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 232 × 3
   variable       n_missing pct_missing
   &lt;chr&gt;              &lt;int&gt;       &lt;dbl&gt;
 1 q112                  89        3.68
 2 q109                  89        3.68
 3 dem                   86        3.56
 4 born_again            83        3.44
 5 livew_guns            82        3.39
 6 no_known_gay          82        3.39
 7 gay_friend            82        3.39
 8 gay_fam               82        3.39
 9 no_known_trans        82        3.39
10 trans_friend          82        3.39
# ℹ 222 more rows</code></pre>
</div>
</div>
<p>If you went sub 1/3 the median, have progress less than 100 and answered fewer than all 3 attention checks (or failed), probably should go.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
</div>
<p>only 4 people</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2412</code></pre>
</div>
</div>
<p>down to 2412 respondents</p>
<p>NOTE TO SELF: Have still not excluded all sub 1/3 the median.</p>
<p>85 ??? Sept 14 – you can come back to this later, for now focus on what’s up without these 85, apply the rule, talk about differences between remaining all answer and remaining only answer controls</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2327</code></pre>
</div>
</div>
<p>n is 2,327</p>
<p>(dropped th 85)</p>
</section>
</section>
<section id="save-cleaned_light.csv" class="level1">
<h1>4. SAVE: cleaned_light.csv</h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  [1] "progress"                   "duration_in_seconds"       
  [3] "finished"                   "response_id"               
  [5] "incarc_raw"                 "knowincarc_raw"            
  [7] "noincarc_raw"               "vict_raw"                  
  [9] "knowvict_raw"               "novict_raw"                
 [11] "on_medicaid"                "knowmedicaid"              
 [13] "no_medicaid"                "tanf"                      
 [15] "knowtanf"                   "notanf"                    
 [17] "snap"                       "knowsnap"                  
 [19] "nosnap"                     "immigrated"                
 [21] "knowimmigrated"             "noimmigrated"              
 [23] "unionmember"                "knowunion"                 
 [25] "nounion"                    "aborted"                   
 [27] "knowaborted"                "noaborted"                 
 [29] "unemployed"                 "knowunemployed"            
 [31] "nounemployed"               "uninsured"                 
 [33] "knowuninsured"              "nouninsured"               
 [35] "unable_vote"                "know_unable_vote"          
 [37] "no_unable_vote"             "ration_scripts"            
 [39] "ration_period"              "ration_food"               
 [41] "q9"                         "q102_1"                    
 [43] "q102_2"                     "q102_3"                    
 [45] "q102_4"                     "q102_5"                    
 [47] "local_police"               "no_strangle"               
 [49] "police_tracker"             "police_training"           
 [51] "charge_police"              "prison_purpose"            
 [53] "dpen"                       "min_wage"                  
 [55] "free_calls"                 "ed_funds"                  
 [57] "lwop"                       "alt_sentencing"            
 [59] "q17"                        "medicare"                  
 [61] "unemployment_ins"           "medicaid"                  
 [63] "reduce_ineq_minwage"        "reduce_ineq_studdebt"      
 [65] "reduce_ineq_taxrich"        "reduce_ineq_moremedcare"   
 [67] "reduce_ineq_lessmig"        "reduce_ineq_poorben"       
 [69] "reduce_ineq_morecoll"       "auto_reg"                  
 [71] "post_felony_vote"           "early_vote"                
 [73] "election_holiday"           "voter_id"                  
 [75] "noncit_local"               "jail_access"               
 [77] "gun_sales"                  "guns_1"                    
 [79] "guns_2"                     "guns_3"                    
 [81] "guns_4"                     "guns_5"                    
 [83] "guns_6"                     "abortion_op"               
 [85] "abortion_death"             "abortion_health"           
 [87] "abortion_rape"              "abortion_defect"           
 [89] "abortion_miscar"            "abortion_debt"             
 [91] "abortion_violence"          "abortion_incarc"           
 [93] "abortion_teen"              "abortion_want"             
 [95] "abortion_ability"           "lgbt_employers"            
 [97] "lgbt_medical"               "lgbt_business"             
 [99] "college_econ_wellbeing"     "college_indoctrination"    
[101] "more_attend_college"        "college_diverse_students"  
[103] "public_college_funding"     "college_no_race_admissions"
[105] "college_ben_beat_costs"     "colleges_out_touch"        
[107] "reg_banks"                  "reg_socmedia"              
[109] "reg_six_fig"                "reg_biz"                   
[111] "increase_deportations"      "increase_border_security"  
[113] "accept_refugees"            "easier_family_sponsorship" 
[115] "allow_daca_stay"            "legal_status_undocumented" 
[117] "gets_issues"                "gov_attn"                  
[119] "vote2020"                   "willvote"                  
[121] "fire_rare"                  "fire_privilege"            
[123] "fire_angry"                 "fire_fear"                 
[125] "q112"                       "aa_special_favors"         
[127] "aa_been_cheated"            "aa_try_harder"             
[129] "legacy_slavery"             "women_power"               
[131] "women_xagg"                 "women_leash"               
[133] "feminist"                   "fiscal_ideology"           
[135] "social_ideology"            "facebook"                  
[137] "twitter"                    "youtube"                   
[139] "q114_4"                     "truthsocial"               
[141] "parlor1"                    "reddit"                    
[143] "tiktok"                     "parlor2"                   
[145] "livew_guns"                 "no_known_gay"              
[147] "gay_friend"                 "gay_fam"                   
[149] "no_known_trans"             "trans_friend"              
[151] "trans_fam"                  "dem101"                    
[153] "dem"                        "q109"                      
[155] "self_ideo"                  "White"                     
[157] "Black"                      "Native_Am"                 
[159] "Asian_Am"                   "Pac_Island"                
[161] "MENA"                       "Hisp_Latino"               
[163] "race_notlisted"             "q51_8_text"                
[165] "relig"                      "relig_text"                
[167] "born_again"                 "relig_import"              
[169] "q113_first_click"           "q113_last_click"           
[171] "q113_page_submit"           "q113_click_count"          
[173] "trans"                      "woman"                     
[175] "man"                        "gqueer"                    
[177] "g_other"                    "q56_4_text"                
[179] "hetero"                     "lesbian"                   
[181] "bi"                         "gay"                       
[183] "queer"                      "other_sexuality"           
[185] "q78_6_text"                 "q58_1"                     
[187] "q58_2"                      "respondent_id"             
[189] "state"                      "county"                    
[191] "block"                      "attn_q9_pass"              
[193] "attn_q9_typo"               "attn_check_q17"            
[195] "attn_q114_pass"             "attn_q9_answered"          
[197] "attn_q17_answered"          "attn_q114_answered"        
[199] "attn_pass_count"            "attn_fail_count"           
[201] "attn_answered_count"        "duration_minutes"          
[203] "sub_8.45"                   "sub_12.6"                  
[205] "sub_20"                     "sub_30"                    
[207] "over_52"                    "over_180"                  
[209] "nonfinisher"                "d_black_afam_abc"          
[211] "d_native_ind_abc"           "d_asianam_abc"             
[213] "d_latino_his_abc"           "d_whiteam_abc"             
[215] "d_mideastam_abc"            "d_incwomen_abc"            
[217] "d_collegewom_abc"           "d_enviro_abc"              
[219] "d_feminists_abc"            "d_proabort_choice_abc"     
[221] "d_abortprov_abc"            "d_welfare_tanf_abc"        
[223] "d_fstamps_snap_abc"         "d_unions_abc"              
[225] "d_medicaid_abc"             "d_medicare_abc"            
[227] "d_unemployed_abc"           "d_police_abc"              
[229] "d_poorfam_abc"              "d_wealthy_abc"             
[231] "d_teachers_abc"             "d_sci_experts_abc"         
[233] "d_child_abc"                "d_crim_abc"                
[235] "d_incppl_pris_abc"          "d_homeless_abc"            
[237] "d_immigrants_abc"           "d_unauth_undoc_abc"        
[239] "d_gunowners_abc"            "d_voters_abc"              
[241] "d_lgbt_abc"                 "d_trans_abc"               
[243] "d_transkids_abc"            "d_gunmans_abc"             
[245] "d_ice_abc"                  "d_socmed_abc"              
[247] "d_nra_abc"                  "d_bigbank_abc"             
[249] "d_bigcorp_abc"              "d_uni_abc"                 
[251] "d_comcoll_abc"              "d_noncit_parent_a"         
[253] "d_incparents_a"             "d_hsteen_a"                
[255] "d_athiest_a"                "d_cath_a"                  
[257] "d_evan_a"                   "d_jews_a"                  
[259] "d_pal_a"                    "d_muslim_a"                
[261] "d_blackwom_a"               "d_blackmen_a"              
[263] "d_lds_a"                    "d_longcov_a"               
[265] "d_exon_a"                   "d_weed_a"                  
[267] "d_opioid_a"                 "d_whitecol_a"              
[269] "d_tech_a"                   "d_smokers_a"               
[271] "d_genx_a"                   "d_boomer_a"                
[273] "d_mill_a"                   "d_genz_a"                  
[275] "d_metoo_b"                  "d_christnat_b"             
[277] "d_ruralam_b"                "d_urbanam_b"               
[279] "d_suburbam_b"               "d_billion_b"               
[281] "d_blm_b"                    "d_maga_b"                  
[283] "d_progs_b"                  "d_soc_b"                   
[285] "d_proudboys_b"              "d_attnys_b"                
[287] "d_military_b"               "d_vets_b"                  
[289] "d_solds_b"                  "d_essentials_b"            
[291] "d_nurses_b"                 "d_drs_b"                   
[293] "d_dems_b"                   "d_reps_b"                  
[295] "d_media_b"                  "d_bluecol_c"               
[297] "d_working_c"                "d_midclass_c"              
[299] "d_migrantwork_c"            "d_smallbiz_c"              
[301] "d_taxpayers_c"              "d_elderly_c"               
[303] "d_moms_c"                   "d_retires_c"               
[305] "d_sexoffenders_c"           "d_sexhar_vict_c"           
[307] "d_sexharrasser_c"           "d_formerlyinc_c"           
[309] "d_homeown_c"                "d_regufee_c"               
[311] "d_gunvi_vict_c"             "d_polbrut_vict_c"          
[313] "d_unins_c"                  "d_mentill_c"               
[315] "d_aids_c"                   "d_gay_c"                   
[317] "d_lesbians_c"               "common_na_count"           
[319] "block_na_count"             "na_count"                  
[321] "attn_wrong_count"           "breakoff"                  
[323] "early_breakoff"             "sub_mean_breakoff"         
[325] "exclude_fast_no_attn"       "exclude_fast_bad_attn"     
[327] "exclude_fast_incomplete"   </code></pre>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>