---
title: "victimization"
author: 
  Kristina Mensik  
  Department of Political Science, Duke University
format:
  pdf:
    pdf-engine: pdflatex
    include-in-header: header.tex
    keep-tex: true
    toc: false
    number-sections: false
    fig-cap-location: top
    booktabs: true
  docx: 
    reference-doc: reference.docx
    toc: false
    number-sections: true
bibliography: references_repaired.bib
csl: apsr.csl
---

## Introduction

Personal experience with carceral policy in the United States is extensive. By year-end 2001, more than 5.6 million U.S. adults had served time in a state or federal prison (BOP 2003), and by 2010, an estimated 8 % had a felony conviction and 3 % had served or were serving prison time (Shannon et al 2017). While systematized data on non-felony convictions remain, as Stenson and Mayson (2018) put it, "absurdly, embarassingly" (p. 732) elusive, they estimate 13.2 million such cases are filed annually. Many millions more experience incarceration indirectly – through proximal contact – as family, friends, or neighbors of those incarcerated – or through victimization, having been harmed by a crime prosecuted by the state. While the interests of these two groups are regularly presented as oppositional, we actually know very little about how these experiences – incarceration, proximal carceral contact, and victimization – shape how people think about criminal legal policy.

Scholars have shown that an important driver of public support for state intervention across other domains is people's beliefs about whether a given target group is *deserving* of policy help or punishment [@desante2013; @ellis2020a]. Further still, such deservingness perceptions often predict state policy outcomes [@kreitzer2022]. These perceptions of deservingness are not purely personal – they are shaped by myriad factors including policy designs themselves [@schneider2019]. Yet, while scholars have shown that deservingness perceptions inform opinions about social welfare, immigration, and even gun policy [@oorschot2000; @kreitzer2022a], the role of deservingness in the criminal legal context remains less well-developed. In particular, we do not know how people’s experiences with the carceral state—either through direct or proximal contact—shape perceptions of deservingness when it comes to criminal justice policy.

Recent work [@sorelle2024] suggests that experience with policy may condition the logics people use to assess deservingness – and that the role of personal experience in deservingness remains underexplored. At the same time, a growing body of scholarship demonstrates how contact with the carceral state shapes people's political attitudes [@weaver2010], political identities [@owens2014], and political engagement [@white2019]. Through what these scholars term policy feedback effects, policies, once enacted, reshape politics by redistributing resources and sending interpretive signals that affect how individuals understand their – and other's – relationship to the state [@skocpol1992; @pierson1993a; @mettler2023a].

This paper brings deservingness and policy feedback frameworks together to understand how direct and proximate experiences of incarceration and victimization shape perceptions of the deservingness of incarcerated people, and whether these perceptions translate to opinions on prison policy. I start with the contention that people form views about policy by quickly judging social constructions of that policy's target group [@schneider1993]. **Drawing on findings that carceral contact can drive perceptions of carceral state illegitimacy and contact group solidarity, I suggest that it may too generate perceptions of carceral targets as more deserving.** Moreover, impacted groups learn these political messages by interacting with policy design. They may in turn have different reference points for carceral policy, and the conditions and consequences of imprisonment. In turn, I expect that carceral contact will translate to more generous perceptions of deservingness of, and consistent support for policy that helps carceral citizens.

I test these propositions using original 2024 survey data capturing Americans' experiences with the carceral system, their perceptions of a range of policy targets, and their attitudes towards prison-related policy reforms. The data allow for a unique empirical examination of how deservingness judgements may vary across direct and indirect experiences with incarceration and victimization – and how these judgements structure policy preferences.

In doing so, this paper makes three contributions. First, it extends theories of social constructions and deservingness – the latter of which was largely developed in the context of welfare and redistributive policy - into the domain of criminal legal policy. Second, it sheds new light on how policy or institutional experience and proximity modifies deservingness perceptions and their correspondence to substantive policy views. Last, it responds to recent interventions that experiences of victimization constitute a critical but understudied component of this feedback loop [@levine] and deepens our understanding of how victimization as a kind of proximal contact of its own can alter the public's orientation toward punishment, policy, and state legitimacy. Understanding how impacted groups differ in their approach to policy – and whether the preferences of most victims and perpetrators are as far apart as dominant narratives would suggest – is important not only for scholars but also for advocates and policymakers pursuing policy reform in this domain.

The remainder of this paper proceeds as follows. In section 2, I elaborate first on key findings from social constructions and deservingness, before discussing policy feedback literature and its implications – particularly, the literature's its conceptualization of policy targets as active agents in meaning-making processes and empirical findings in the criminal legal domain – for my expectations about criminal legal policy. I develop theoretical framework, outlining how carceral contact may shape perceptions of deservingness and how those perceptions may, in turn, influence policy views. Section 3 then presents the data and analytic strategy, drawing on a newly fielded national survey to test these relationships. I conclude in section 5 with a brief discussion of implications for theories of deservingness, policy feedback, the politics of punishment.

## Deservingness and Attitudes Towards Public Policy

How does contact with the criminal legal system affect perceptions of its targets? And what do these deservingness perceptions mean for policy views? Scholarship of the social constructions of target populations and deservingness respectively examine how groups become characterized as deserving or undeserving of government assistance, and they demonstrate that people's policy preferences often hinge on such characterizations [@schneider1993a; @smith2024; @vanoorschot2006].

Schneider and Ingram's (1993) theory of social constructions locates perceptions of target deservingness in a dialectic with policy design. That is, public perceptions of whether policy targets are deserving or undeserving are informed by social constructions, or "value-laden components, including stereotypes, dominant ideologies, and assumptions" about groups (Smith and Kreitzer 2024, p. 640). Policymakers are attentive to these perceptions, as they expect their constituencies to electorally reward them for producing policy that helps deserving groups like veterans, and refraining from offering help to or punishing the least deserving – particularly "deviant" groups like carceral citizens[^1]. Thus, policy re-enforces perceptions of deservingness, by "telegraph\[ing\] to the public how target groups should be treated" (Smith and Kreitzer 2024, p. 640). While, as a consequence, particularly negative social constructions like those of carceral citizens may become "sticky" or more entrenched, social constructions are also contingent, for example, on local, state, and political and cultural contexts and also on the political identity of and ideology held by the 'perceiver' (Smith and Kreitzer 2018, p. 768). Thus, the relevant social construction driving perceptions of deservingness may different across audiences and policy contexts.

[^1]: Schneider and Ingram's theory of social construction goes on to note that policymakers respond not only to their constituencies' perceptions of target deservingness, but also to the political power of target groups, or their ability to ability to access, reward, and/or retaliate against policymakers. These interacting dimensions (power and deservingness) produce four categories of groups in society, to whom policy makers respond with distinct policy. Policymakers are incentivized to help groups who are “advantaged” – both powerful and perceived as deserving -- and “contender” groups, or those who are powerful but constructed as undeserving. In contrast, policymakers offer burdensome policy to “dependents” – those who are seen as deserving but who are not politically powerful, and punish “deviants,” who are seen as neither deserving nor powerful. Political representatives’ policy design is also driven by “anticipatory” feedback: policymakers respond to both their perception of groups’ political power and social constructions in terms of electoral consequences – for example, by providing “hidden” benefits to contenders, who are constructed as undeserving but powerful, policymakers can avoid political blowback for helping an “undeserving” group while strengthen their own political position. (Schneider and Ingram 2019, Ellis and Faricy 2020).

While social construction scholars helps illustrate external mechanisms that may drive broad constructions of carceral citizens' deservingness, others have paid more attention to specific mechanisms shaping how people judge whether policy targets are deserving. This line of deservingness scholarship explains that people form quick judgements about policy targets' deservingness by evaluating constructions along five dimensions in an evolutionarily-grounded impulse to help "reciprocators" and avoid "free-riders" [@petersen2012; @petersen2012]. These "CARIN" criteria primarily attend to cues about whether recipients cannot help their circumstances, or whether they are seeking unearned benefits. They refer to: *control,* which in its original conception was closely related to *need*, referring to whether someone is perceived as lazy or unlucky – a consideration Oorschot (2006) argues can override all others. More recently, perception of a group or individual’s *need* for assistance has considered the severity of their neediness and *control,* or the degree to which they are responsible (SoRelle and Laws 2024). Perceptions of the group’s *attitude* refer to whether the beneficiary is grateful and likeable, and closely related perceptions of the group’s *reciprocity* connote their history or apparent willingness to contribute to society. Last, the *identity* characteristic holds that people will evaluate more generously the deservingness of others whose identity is aligned with their own (Oorschot 2000, 2006). While this framework originated to explain views of welfare policies, scholars have applied it to explain policy views in other areas of social policy, including health care [@gollust2011].

## From Social Constructions of Deservingness to Policy Feedback

My theoretical starting point is that perceptions of what groups like carceral citizens deserve are often shaped by social constructions about them (Schneider and Ingram 1993) . Like stereotypes, these constructions are produced by policy and discourse – both political, cultural, and popular – and they are often taken up by individuals in a heuristic process to form quick judgements about what a target group deserves. Thus, predominant racialized constructions of incarcerated people – “thugs,” “felons,” or “inmates,” – that invoke ingratitude, self-orientation, and blameworthy-ness for their condition of confinement are likely interpolated as undeserving.[^2]

[^2]: In the criminal legal domain, these representations are often shaped by racialized media portrayals and political discourse that emphasize danger and individual blame (Lopez 2015; Vasiljevic and Viki 2014).

Desesrvingness literature may suggest one direct pathway through which contact might interrupt this process. Simply put, someone who is in and knows people in prison has access to information about who an incarcerated personal is outside of their "criminal" identity in a way that someone who has only seen "prisoners" on TV may not. Carceral state contact should, by definition, change what information individuals have about its targets. This alone could translate to more generous interpretations of deservingness [@oorschot2000b; @vanoorschot2006b; @feather2009a]. [^3] Following Schneider and Ingram (1993), these deservingness perceptions then influence how individuals evaluate related criminal legal policies.

[^3]: For example, contact may lead individuals to see incarcerated people as facing substantial hardships (*need*), with less control over the conditions that led to incarceration (*control*), and as capable of gratitude, growth, or giving back (*reciprocity*, *attitude*). In contrast to dominant constructions that depict incarcerated people as undeserving, contact may “fill in” these criteria with lived or vicarious knowledge. On this dimension, then, contact may generate warmer deservingness perceptions by replacing stereotypes with personalized, alternative narratives about who carceral citizens are and what their conditions and the consequences of confinement.

Yet it is important to note that this logic implicitly assumes that the processes by which deservingness is interpreted and shapes policy views operate the same way in the criminal legal domain as they do in the welfare state, where much of deservingness literature originated. Recent work complicates that assumption. Schneider and Ingram (2019) note that even "deviant" groups – long presumed to be negatively constructed – can become beneficiaries of policy help, especially when costs, visibility, or broader group associations shift. SoRelle and Laws (2023) observe that perceptions of individual deservingness may not linearly translate into support for policy overall. Together, these insights suggest the need not only to examine whether contact reshapes perceptions of deservingness, but also to assess how — and whether — those perceptions relate to support for state intervention in the carceral domain. Yet what remains less fully theorized is whether, and how, the meaning and influence of these social constructions differ for individuals who have direct experience with the relevant policy. Might experiences with policy change how these constructions and characteristics are interpreted, or the extent to which they are internalized and interpolated into policy views? Lessons from policy feedback literature suggest they might.

Across domains, including the carceral state, policy feedback literature shows that policies can shape attitudes towards the state and institutions, one's sense of "civic self," and political behavior as part of a process through which policies, once established, have the capacity to shape and reshape policy landscapes [@campbell2012; @skocpol1992]. These "feedbacks" operate through two core mechanisms: resource effects, which concern the distribution of material benefits and costs, which can enact barriers or incentives to participation, and interpretive effects, which concern the ability of policy design to convey messages to its targets about their civic standing, and what they can expect and may ask of government as a whole [@campbell2011; @mettler2004; @mallorysorelle2022].

This interpretive element offers an extension of social construction theory, in that it suggests that the messages a policy target infers from interacting with policy are unique, and should not be inferred to mirror the messages policy conveys about to broader audiences its targets. Moreover, this framework positions policy targets as "active agents" in the construction of meaning who internalize and respond to policy messages in different ways – by rejecting a negative construction or its policy implication and engaging in collective action, or conversely by differentiating onesself and disaggregating one's overall policy views from their perceptions of beneficiary deservingness [@soss1999; @goss2012; @thurston2018; @sorelle2020; @lacombe2022].[^4]

[^4]: Soss (1999) explains a tendancy of recipients of means-tested welfare (AFDC) to maintain negative constructions about beneficiaries of the same policy (unlike recipients of the non-means tested disability benefits) as a product of political learning while on the AFDC: benefits are burdensome to access, involve stringent behavioral monitoring, and involve more caseworker discretion than standardized rules, conveying to AFDC beneficiaries that government views them as responsible for their need and untrustworthy. This leads beneficiaries to not only internalize a more "undeserving" perception of their own beneficiary group, but also splinters any sense of group solidarity and disaggregates policy views from perceptions of beneficiary deservingness.

In the criminal legal domain, scholarly debate around the conditions under which carceral contact is politically mobilizing or demobilizing foregrounds this variation (cf. White 2022). Many carceral citizens, their networks, and neighborhoods internalize the clear "undeserving" messages that prison policy sends [@lee2014; @weaver2010a]. In doing so, feedback scholars also delineate the experiences and outcomes of people with not only direct, but also indirect or "proximate" contact, such as families of targets and neighborhood effects. For example, [@burch2014] finds that high concentrations of incarceration and community supervision reduce political participation, creating “important spillover effects that suppress participation not only of the supervised individual but also of those living around him or her” (197). But others find that both direct and proximal contact can mobilize [@anoll2019; @walker2020; @ewald2024]. While these studies do not focus specifically on the link between contact and deservingness, they are nonetheless theoretically instructive about the role of direct and proximate contact on political behavior.

While many carceral citizens and their networks internalize the clear “undeserving” messages conveyed by criminal legal policy, research increasingly shows that such contact can also shape political attitudes towards the state – fomenting perceptions of institutional illegitimacy [@anoll2019; @anoll2022; @walker2020a; @lerman2014]. As such, I propose that interactions with the carceral system should also shape attitudes towards *targets of the state* – and their legitimacy or deservingness in relation to it. While some work finds that targets of policy can internalize negative or undeserving constructions [@soss1999a], much of the work on criminal legal contact stresses that demobilization is a product of resource effects or interpretive effects *distinct* from an “undeserving” self-conception (Lerman and Weaver 2014, White 2019). Instead, scholars emphasize that direct contact with the criminal legal system can heighten in-group solidarity and mobilize in spite of resource and interpretive feedbacks that should be demobilizing. (Walker 2020, Owens 2014). T**his is specifically the case when policy targets reject policy “teachings” about their lower civic status as part of a sense of systemic injustice – suggesting a reappraisal of both the system and those criminalized by it (Walker 2020).** Among family of the incarcerated, Anoll (2022) suggests that higher rates of voting in states specifically with most stringent carceral disenfranchisement policies suggests “surrogate” mobilization, or a motivation to act on behalf a “deserving” incarcerated citizen, is at work. Thus, mobilization in response to both direct and proximal contact involve meaning-making processes that wed social solidarity with dampened perceptions of institutional legitimacy and trust.

But interaction with the carceral system may facilitate not just political, but also policy learning. Targets and their networks come to learn policy messages by experiencing policy burdens. Lee et al. (2014), for example, find that demobilizing 'spillover effects" are trace to family and loved ones of the incarcerated experiences with and reaction to policies whose costs they incur, like those of visitation, expensive phone calls, and paying off fines and fees. That the experiences producing political responses are grounded in personal experience with policy suggest that contact may reorient how individuals think about policy, as it changes what they think (for example, what consequences to policy they imagine) when they think about policy.

Feedback scholars acknowledge endogeneity challenges inherent to questions of carceral state contact in a context of "cumulative burdens" or where the same individuals and communities often experience both direct and proximate carceral contact [@michener2018; @weaver2010b; @lerman2014b]. These experiences in isolation may have important differences. While some note psychological motivations the incarcerated may have to hold deserving perceptions of themselves and others [@maltby2023],[^5] others stress that they may be far more likely to internalize undeserving messages, from which the proximally impacted may be more removed [@anoll2019a; @anoll2022a; @walker2017; @walker2016; @walker2014; @walker2017]. Experiences of victimization amplify this tension: they often occur alongside policing and incarceration in the same communities, yet are rarely conceptualized as a form of policy contact in their own right.[^6]

[^5]: Maltby and Kreitzer (2023) also take up the question of carceral contact’s effect on target deservingness, several limitations in the design raise ques-tions about whether their findings reflect a measurement artifact. First, the study conflates arrest with incarceration, despite these experiences carrying distinct resource effects, stigma, and lessons vis-a-vis one’s civic standing and government responsiveness (cf. Soss 2005). Further still, arrest may allow for self-distancing and meritocratic narratives, whereas incar-ceration deeply implicates individuals in systems that mark groups as “undeserving” (cf.(Newman, Shah, and Lauterbach 2018))5. Second, the study aggregates deservingness per-ceptions of “criminal legal targets” that includes groups like “opioid users,” “welfare cheats,” and other groups less apt to the relationships of interest: how policy experience shapes per-ceptions of policy target deservingness. Third, their design does not test what these deserv-ingness mean for policy preferences, which given its novel application of deservingness to the carceral contexts, leaves open the question of whether these perceptions mean the same thing in the criminal legal domain. Further still, the study does not distinguish between dif-ferent types of contact, such as incarceration versus victimization. These limitations reflect a broader pattern in the literature, where the effects of carceral contact — especially forms like victimization — remain theoretically and empirically underdeveloped.

[^6]: One notable exception is Levine and Russell (2023), who show how the design and financing of victim compensation law constructs victims as morally deserving and politically worthy, helping expand state responsibility. Yet even here, the analysis centers on state building and symbolic policy meaning—rather than how victimization itself may function as a form of lived experience that may alter how individuals perceive the state, its targets, and what policies they deserve.

Although victims of crime are rarely theorized as policy feedback subjects, the concept of victimization is implicitly central to the literature. Policy feedback scholars emphasize how individuals interpret state actions—especially punitive or discriminatory ones—as signals of exclusion, abandonment, or devaluation [@soss1999b; @lerman2014a]. These “interpretive effects” can leave people feeling targeted, disrespected, or undeserving in the eyes of the state. In this context, experiences of secondary victimization—such as being disbelieved, ignored, or emotionally constrained by the criminal justice process [@lensa] — can function much like the demobilizing interpretive effects faced by other negatively constructed policy targets. Yet unlike welfare recipients or formerly incarcerated people, crime victims are more often assumed to support the very policies and institutions that may reproduce their harm. Recognizing victimization as a form of state contact—and a potential site of interpretive rupture—opens new terrain for understanding how criminal legal experience shapes not only institutional trust and political participation, but also deservingness perceptions and carceral policy attitudes. This paper takes up that challenge by analyzing victimization alongside other forms of contact to assess how they each influence perceptions of who deserves help or harm—and what role the state should play.

## Hypotheses

How does contact shape perceptions of what carceral citizens deserve? While views on criminal legal policy and how people conceive of carceral citizens are complicated questions, I anticipate that these experiences (incarceration, neigborhhood or social connections to the incarcerated, and victimization), depress the authority of carceral policy design to convey meaning about its targets. Perceptions of systemic injustice and trends of surrogate participation suggest contact may generate more nuanced perceptions of deservingness in its own right, as carceral citizens are conceived of as victims of injustice and or deserving of representation. While individuals within these groups may still respond to policy messages and think about targets in different ways, I expect these groups to view carceral citizens as more deserving than those without impact. Because people with proximate impact may be less likely to internalize undeserving messages, they may have warmer perceptions than the directly impacted. Further, I suggest that experience with the criminal legal system – including victimization – leads people to stronger and more consistent support for offering policy help to help incarcerated people, and to more nuanced ways of thinking about the relationship between what a carceral target 'deserves' and what policy is appropriate.

Respondents with no direct or proximate experience with incarceration may rely more heavily on dominant public narratives that portray incarcerated individuals as violent, morally deficient, or socially deviant. Social construction theory suggests that, in the absence of countervailing personal experiences, people turn to culturally available representations to evaluate policy targets (Schneider and Ingram 1993; Smith and Kreitzer 2024). In the criminal legal domain, these representations are often shaped by racialized media portrayals and political discourse that emphasize danger and individual blame [@ghandnoosh2014]. Without lived or relational knowledge to “fill in” CARIN criteria such as control, reciprocity, or need with humanized nuance, these respondents are more likely to default to punitive or stigmatized constructions of incarcerated people. Even those who know only victims of crime may be exposed to narratives emphasizing offender culpability and just deserts—without the complexity that comes from understanding incarcerated people as multifaceted individuals. Therefore, I expect that:

***H1*** *Direct and proximate experiences with incarceration and experiencing victimization will lead to more generous deservingness perceptions of incarcerated people.*

***H1-A*** *Individuals with proximate impact will report more deservingness perceptions of incarcerated people. than those who are directly impacted.*

While victimization might intuitively drive negative perceptions of carceral citizens, I suggest the relationship is more complex.

Researchers provide evidence that more abstracted, dehumanized stereotypes about carceral citizens (Vasiljevic and Viki 2014) generate harsher assessments of culpability [@levinson2007; @levinson2010; @donovan2007; @israel-trummel2022] and sentences (Rehavi and Starr 2014) suggesting that information *besides* conviction and crime about carceral citizens should have a countervailing humanizing effect [@manza2006].

However, there are clear reasons why victimization may generate *undeserving* perceptions: victimization is highly a salient experience that for many drives negative affect toward those who commit crimes [@ditton1999] and provides a clear justification to focus on criminal culpability when considering incarcerated people overall [@culhane2004]. However, this logic assumes clear victim-offender boundaries and risks ignoring the broader social context in which violence occurs. The overlap between victims and otherwise impacted groups is significant [@jennings2012]. Victims of violent crime are disproportionately part of communities most heavily policed and incarcerated and most know their offender (Bureau of Justice 2024) – most individuals who experience incarceration have also been victimized, as well.[^7] Thus, while for many victims the proximity and salience of a 'criminal' may bolster negative social constructions and deservingness perceptions, it might also translate to more nuanced perceptions of culpability and a closer alignment of identity that moderates negative affect.

[^7]: An extensive literature shows that people who are incarcerated have disproportionately been victims of crime – one review article cited 31 of 37 papers support this overlap (Jennings et al 2012). While 2% of the general US population report being victims of violent crime, up to 45% of carceral citizens have experienced pre-incarceration physical abuse, and 8.5 to 39.2% of specifically sexual abuse (Azimi et al 2019, Carlson and Shafer 2010, Messina et al 2007, Wolff and Shi 2012, Yoder et al. 2017). Still more experience violence while incarcerated (Wolff et al 2009).

Moreover, victims face restrictive, "sticky" social constructions – what Lens et al (2014) note generate negative feedbacks. While navigating narrow expectations of "appropriate" emotional responses in the criminal justice process – non-emotional victims risk disbelief while overly emotional victims face judgment – victims experience "secondary victimizations" that foment institutional distrust. In this way, victims may come to share with incarcerated individuals not only carceral exposure, but also skepticism toward the system itself and its moral judgments about who is or isn’t deserving (Walker 2020; Anoll & Israel-Trummel 2019). For some, this may produce more nuanced assessments of incarcerated people as victims of systemic injustice rather than mere perpetrators. For others, especially those who strongly identify with retributive justice or lack personal connection to offenders, deservingness perceptions may remain harsher. However, it is worth noting that victimization generally does not increase punitiveness – and that instead perceptions of crime are more important in driving punitive sentiment than actual crime - suggesting victimization may both lead to more moderated perceptions of carceral citizens and perceptions of what they deserve [@hale1996; @kleck2017a; @kleck2017]. I therefore expect that:

***H1-B** Victims of violent crime may vary more than other impacted groups in their perceptions of incarcerated people’s deservingness, but on average, will still express more generous views than individuals with no direct or proximate contact with the carceral system.*

Social construction theory suggests that perceptions of target deservingness translate directly to policy preferences: groups constructed as undeserving receive punitive policy while deserving groups receive beneficial policy (Schneider and Ingram 1993). Applied to the carceral domain, this means that warmer perceptions of incarcerated people's deservingness predict greater support for policies that help rather than punish them. Thus, deservingness acts as a mediating bridge between group perception and carceral policy support. I therefore hypothesize that:

***H2** More generous perceptions of carceral citizens' deservingness will predict greater and more consistent support for assistance-oriented criminal legal policies and reduced support for punitive criminal legal policies.*

However, evidence from SoRelle and Laws (2023) and others suggests the relationship between deservingness perceptions and policy support may not be straightforward in all contexts. The criminal legal domain may have unique dynamics where perceptions of groups and support for policies directed at them operate through different mechanisms.
