---
title: "test"
author: "Kristina Mensik03"
date: "2025-04-06"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Contact with carceral policy in the United States is extensive. At year end 2001, more than 5.6 million U.S. adults had served time in a state or federal prison (BOP 2003). Many millions more experience incarceration through proximal contact – because they have a family member or friend who is incarcerated, or because they were the victim of a crime prosecuted by the state. This direct and proximal carceral contact has generated a significant scholarship in recent years that attempts to understand how contact with this particular state policy feeds back to shape attitudes towards the state (*cite*), attitudes towards policies (*cite*), and political engagement (*cite*).

Implicit in much of this carceral policy feedback literature is the contention that attitudes and engagement are shaped by perceptions of what the targets of state policy *deserve*. Across numerous policy domains, individuals report being more willing to support policy when the targets of that policy are viewed as deserving (cite). Yet, there is limited evidence on how carceral contact, specifically, shapes perceptions of deservingness and the extent to which these perceptions drive policy views. Further still (victimization).

This paper addresses these X gaps. To do so, I ask how direct and proximate experiences of incarceration and victimization shape perceptions of the deservingness of incarcerated people, and whether these perceptions translate to opinions on prison policy. Employing and connecting both deservingnness and policy feedback frameworks, I theorize that as carceral contact can drive perceptions of carceral state *il*legitimacy and distrust, it may too engender warmer perceptions of carceral targets. Further still, direct and proximal contact in the form of both incarceration and victimization may allow for more nuanced perceptions of who carceral targets are and what policy help they, or the interest of public justice and safety, need – irregardless of carceral targets perceived deserving status. In otherwords, the relationship between target deservingness and policy views may look different than in others, and across contact groups. I test these relationships using newly collected 2024 data on perceptions of target group deservingness, policy experiences, and policy preferences across the states.

In doing so, I contribute to literature on social constructions and deservingness, in which scholars are exploring the extent to which theories rooted in welfare provision apply to other domains, testing the extent to which deservingness perceptions mediate policy opinions, and, interleaved with policy feedback literature, whether those who are "closest to the pain" or have first-hand experience with policy differ from those who do not. I also shed new light on two unexamined components of policy feedback of the carceral state: whether contact shapes views on criminal legal policy, and feedback effects of victimization.

My theoretical starting point is that perceptions of what groups like carceral citizens deserve are often based on discursive social constructions about them (Schneider and Ingram, 1993). Policy directly shapes these constructions, as it produces both resource and interpretive feedback effects that are part of the discourse that shapes constructions. In forming opinions about policy and deciding what inequalities are tolerable, publics draw on salient social constructions about the relevant policy target and use them in a heuristic process to quickly determine whether a target is “deserving” of help (citation). Theoretically, then these judgements translate to, or at play in the formation of, beliefs about criminal legal policy.

Here, I suggest that this loop between policy design and the messages it transmits about what it’s targets deserve may be interrupted for some citizens due to their connections to those who are justice involved, Emerging evidence that *responses to* the criminal legal system’s policy messages vary, and specifically that some respond to the negative messages transmitted by criminal legal policy with dubiousness towards state legitimacy suggest perceptions of what its targets deserve may vary as well (Walker 2020, Harris 2025).

. . .

# Literature

How does contact with the criminal legal system affect perceptions of it's targets deserve? And what do these deservingness perceptions mean for policy views? These questions intersect with two literatures. First, scholarship on social constructions and deservingness examine how groups become characterized as deserving or undeserving of government assistance, and theorizes that both policy views and outcomes hinge on such characterizations (Schneider and Ingram 1993, Smith and Kreitzer 2024, Oorschot 2006). While this literature leaves open the question of how individual experiences with policy might alter characterizations about it's targets, lessons from policy feedback literature suggest they might. This closely related literature shows that policies can shape political attitudes and behavior across domains, including that of the carceral state. While these scholars have established true broad mechanisms through which carceral contact indeed influences political participation and institutional trust – "resource" and "interpretive" effects – much less is known about how such contact affects attitudes toward the targets of these policies Specifically, we do not yet understand how direct or proximal experience with incarceration or victimization might reshape perceptions of incarcerated people's deservingness and, in turn, opinions on prison policy. I briefly review these literatures here.

In the wake of Schneider and Ingram's (1993) theory of social constructions, scholars have coalesced around the idea that attitudes towards policy targets are in dialectic with policy. That is, policy design not only has "interpretive effects" on its targets but also shapes discourse *about* them. In this way, policy can "telegraph to the public how target groups should be treated," and helps to produce social constructions or "value-laden components, including stereotypes, dominant ideologies, and assumptions" about groups (Smith and Kreitzer 2024, PAGE). As consequence, social constructions are contingent. They are contingent, for example, on local, state, and political and cultural contexts and also on the political identity of and ideology held by the 'perceiver' (Smith and Kreitzer 2018). This means both that policy can *reflect* existing social constructions, and that it can feed back to causally affect further social constructions of who targets are. The notion of who targets *are* in turn affects how people perceive what they *should* receive – i.e., what they deserve. These perceptions matter because they are theorized to be understood as policy preferences and translated by policymakers into policy that helps or hinders groups, reinforcing their social constructions (Schneider and ingram 2019).

A related stream of literature explains that people form quick judgements about policy targets' deservingness by evaluating constructions along five dimensions in an evolutionarily-grounded impulse to help "reciprocators" and avoid "free-riders" (Petersen 2012, Aaroe and Petersen 2014). These "CARIN" criteria primarily attend to cues about whether recipients cannot help their circumstances, or whether they are seeking unearned benefits. They refer to: *control,* which in its original conception was closely related to *need*, referring to whether someone is perceived as lazy or unlucky – a consideration Oorschot (2006) argues can override all others. More recently, perception of a group or individual’s *need* for assistance has considered the severity of their neediness and *control,* or the degree to which they are responsible (SoRelle and Laws 2024). Perceptions of the group’s *attitude* refer to whether the beneficiary is grateful and likeable, and closely related perceptions of the group’s *reciprocity* connote their history or apparent willingness to contribute to society. Last, the *identity* characteristic holds that people will evaluate more generously the deservingness of others whose identity is aligned with their own (Oorschot 2000, 2006).

Do experiences with policy change how these constructions and characteristics are interpreted? While the deservingness literature on this is limited, there is some evidence it can. In the context of student debt relief, SoRelle and Laws (2023) find that people who have had student loans themselves view borrowers as more deserving of debt forgiveness – reflecting perceived closeness of "identity." Maltby and Kreitzer (2022) find similar effects in the context of welfare, but that such solidaristic effects of policy experience begin to erode when individuals consider beneficiaries of welfare programs that are *different* than one's own – a finding social constructionists may note reflects the "stickiness" of negative constructions of target populations and tendencies to construct more 'deserving' subsets within a population while stigmatizing others (Schneider and Ingram 1990, Matos 2019), or deservingness scholars might explain as a product of shared experience changing what information about a group is implicitly available (Feather 1999, 2009). Recently, however, Schneider and Ingram (2019) have noted more complicated dynamics around negatively constructed – specifically, "deviant" – groups and SoRelle and Laws (2023) further note that deservingness perceptions may not linearly translate into support for policy overall.

Given the criminal legal systems particular [high costs and visibiliy], scholars note that "policy contact" must be understood both in terms of direct contact – arrest, incarceration, fines and fees – and also in terms of proximate contact, or the experiences of the disproportionately Black, Latinx, and low-income social networks and neighborhhoods of the incarcerated (Baumbartner, Epp, and Shoub 2018; Davenport, Soule, and Armstrong 2011, Western et al 2004, Massoglia 2008). A closely related literature on policy feedback offers more insight into this dimension. To better understand how both direct and proximate criminal legal contact may shape perceptions of targets of the system's targets, how contact may shape views on criminal legal policy, and the link between the two, we turn there now.

### Policy Feedback

**Introduce PF: resource, interpretive, direct, proximate**

How might policy experience shape social constructions, perceptions of target deservingness, and produce policy preferences?

Feedback scholars show that across domains, policies have the capacity to shape and reshape subsequent policy landscapes (Skocpol 1992, Campbell 2012). This increasingly wide-reaching scholarship shows that whether responding to visible or hidden policy, or produce first or second-order actual or noneffects, such "feedbacks" operate through two broad mechanisms (Mettler 2011, Soss and Schram 2007, SoRelle 2020, 2021). First, policies create resource effects: policies distribute benefits and imposing costs that can alter political capacities, and create incentives or disincentives to political engagement – costs incurred in domains that are not strictly "political" have political ramifications (Campbell 2003, Mettler 2005). Similarly, "interpretive" effects connote the ability of policy design and implementation to convey messages to it's targets about what they can expect and may ask of government as a whole. This interpretive element involves but is distinct from social construction theory, in that it stresses the messages a policy target translates from interacting with policy, rather than the more general messages conveyed *about* targets from policy.

It follows that policy feedback scholarship notes that targets may respond to policy design by rejecting a negative construction or message imbued in or derived from it, and engage in collective action (Goss 2013, Thurston 2018, SoRelle 2020, Lacombe 2021). Of course, this is not always the case: Soss (1999) explains a tendancy of recipients of specifically means-tested welfare (AFDC) to maintain negative constructions about beneficiaries of the same policy (unlike recipients of the non-means tested disability benefits) as a product of political learning while on the AFDC: benefits are burdensome to access, involve stringent behavioral monitoring, and involve more caseworker discretion than standardized rules, conveying to AFDC beneficiaries that government views them as responsible for their need and untrustworthy. This leads beneficiaries to not only internalize a more "undeserving" perception of their own beneficiary group, but also splinters any sense of group solidarity and disaggregates policy views from perceptions of beneficiary deservingness.

Further, feedback scholarship dilineates distinctions between feedback effects of direct policy contact, versus "proximate" contact such families of targets and neighborhood effects. This is particularly so in the literature on policy feedbacks of the carceral state.

Proximate

Direct Debate

AM – HERE: think abt what you will need to critique from R+K (policy design). can do a "in xyz example" and talk briefly about Soss. Also remember to have distinct section on proximate.

**CJ Policy Feedback**

The criminal legal
