---
title: "scratch march 30"
format: html
editor: visual
---

## Scratch

In the US, Black, Latinx, and low-income communities bear the disproportionate brunt of policing and incarceration (Gelman, Fagan, and Kiss 2007, Baumgartner, Epp, and Shoub 2018, Davenport, Soule, and Armstrong 2011). Noting this disparity and those produced by the carceral system’s myriad collateral consequences outside the strictly political domain (Western et al 2004, Massoglia 2008), scholars grounded in policy feedback theory have demonstrated myriad ways the criminal legal system shapes political attitudes and behavior of the people and communities it incarcerates and polices (Lerman and Weaver 2014, White 2019a and b, Michener 2018, Burch 2013, Owens 2014, Walker 2020).  Lerman and Weaver (2014) employ findings that court, police, and prison encounters depress political participation by fostering government distrust and perceptions of a reduced civic status to argue that the carceral state “actively construct\[s\] a different citizenship” (28). Other’s before and since have found that direct interactions with the carceral system, including short stints in jail and encounters with the police like traffic stops depress participation (White 2019, Ben-Menachem and Morris 2023, Rosenthal and Farhart 2022) -- and that these demobilizing effects can extend beyond the individual to their social networks and neighbors (Burch 2014).  

Such demobilization is a result resource effects of carceral contact, like financial burdens or cumbersome processes to reinstate voting rights (Comfort 2008, Page, Piehowski, and Soss, 2019), and interpretive effects -- the messages that policy and institutional designs confer about a its target’s civic standing, the efficacy and responsiveness of government, and thus the merits of political participation. While to my knowledge, no literature argues these effects are experienced or interpreted differently, a growing literature finds that targets’ responses are not unidirectional: visible forms of policing can have mobilizing effects at the community level when it is perceived to be racially discriminatory (Anoll et al 2022), and incarceration can be politically mobilizing despite perceptions of procedural unfairness (Owens 2014, Walker 2020). Both involve meaning-making processes wedding social solidarity with dampened perceptions of institutional legitimacy – what Walker (2020) terms a sense of “systemic injustice.” Among the “proximally” impacted, or those with close social ties to direct targets, like children of incarcerated parents, political mobilization can reflect their own distinct drivers \[fixing this\] (Lee, Porter, and Comfort 2014). Anoll and Israel-Trummel (2019) find evidence such proximate mobilization is a produce of “surrogate” participation, or a motivation to participate specifically on behalf of or due to the disenfranchisement or incarceration of another.

While literature on policy feedbacks of the carceral state has established that contact with criminal legal policies and institutions shape political behavior and attitudes, and that these impacts in turn may re-enforce or change policy outcomes, much less is known about how contact with the criminal legal system have on attitudes towards its *targets*.

In the wake of Schneider and Ingram’s (1993) theory of social constructions, a literature has coalesced around the idea that attitudes towards policy targets are in dialectic with policy. That is policy design not only has “interpretive effects” on its targets but also shapes discourse about them, “telegraph\[ing\] to the public how target groups should be treated,” and producing social constructions or “value-laden components, including stereotypes, dominant ideologies, and assumptions” about groups (Smith and Kreitzer 2024, page). As consequence, social constructions are contingent – for example, on local, state, and political and cultural contexts and also the identity and ideology held by the ‘perceiver’ (Smith and Kreitzer 2018). A related stream of literature explains that publics form quick judgements about policy targets’ deservingness by quickly evaluating constructions along five dimensions (“CARIN”) in an evolutionarily-grounded impulse to help “reciprocators” and avoid “free-riders” by “pay\[ing\] attention to whether welfare recipients are lazy or making an effort” (Petersen 2012, Aaroe and Petersen 2014). These criteria refer to: *control,* which in its original conception was closely related to *need*, referring to whether someone is perceived as lazy or unlucky – a consideration Oorschot (2006) argues can override all others. More recently, perception of a group or individual’s *need* for assistance has been considered the severity of their neediness and *control* the degree to which they are responsible (SoRelle and Laws 2024). Perceptions of the group’s *attitude* refer to whether the beneficiary is grateful and likeable, and closely related perceptions of the group’s *reciprocity* connote their history or apparent willingness to contribute to society. Last, the *identity* characteristic holds that people will evaluate more generously the deservingness of people whose identity is aligned with their own (Oorschot 2000, 2006).

Scholars have built on both social construction and CARIN theories of deservingness to find that experience with a policy can influence how targets of that policy are perceived. In the context of student debt relief, Sorelle and Laws (2023) find that “having had student debt increases both support for government relief and perceptions of borrower deservingness for debt forgiveness (379). Maltby and Kreitzer (2022) find that having once been on welfare increases perceptions of welfare beneficiaries’ deservingness, but that “while feedback effects transfer within a policy domain, certain policy experiences may have particularly strong effects in shaping the perceived deservingness of fellow program recipients” (156). Specifically, they find that respondents who are or have been on welfare view recipients of the same policy or program beneficiaries of others, reflecting either more closely aligned identities, in the CARIN framework, or the ‘stickiness’ of negative social constructions about welfare recipients. In a study of recipients of means-tested welfare (Aid to Families with Dependent Children, or AFDC) and Social Security Disability Insurance (SSDI), Soss (2005) notes that undeserving messages and resources effects unique to AFDC design, like stringent behavioral monitoring and caseworker discretion in lieu of standardized rules, lead its recipients to not only  internalize a more “undeserving” perception of AFDC beneficiaries, but do so to the point they seek to differentiate themselves from other beneficiaries and splinter any sense of beneficiary group solidarity – and splintering their welfare policy views from their views of the deservingness of beneficiaries.

Here, ultimately, perceptions of incarcerated people’s deservingness matter because, the CARIN literature holds, they should explain policy preferences and, the social constructions literature holds, they should explain policy outcomes. According to Schneider and Ingram’s (1993) foundational typology, policymakers are incentivized by electoral politics to produce policy that helps groups who the public sees as deserving, and to decline to help, or to punish, groups who are seen as undeserving.  “Undeserving” policy targets are considered differentiable based on whether they have the political power to influence policymakers (known as “contenders”) or not (known as “deviants”). Incarcerated people fall in the latter category: because deviants are socially constructed as undeserving, and their constituents see deviants as undeserving, policymakers produce punitive policy. However, Schneider and Ingram (2019) themselves recently noted an incongruence in the domain of criminal legal policy, and studies of legislative perceptions and responsiveness, for instance, complicate this relationship by showing that legislators misinterpret public preferences (Broockman and Skovron 2018, Krimmel, Lax and Phillips 2016). On the intermediate step, SoRelle and Laws (2013) also find that perceptions of policy beneficiary deservingness’ do not linearly translate into support for corresponding policy (SoRelle and Laws 2023)

 [\[KM1\]](#_msoanchor_1)Add citations, Owens, early Ewald).
